# Generated by Django 4.1.1 on 2022-09-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0003_rename_list_todoentry_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
