# Generated by Django 4.1.1 on 2022-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_todo_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
