# Generated by Django 4.1.1 on 2022-09-19 07:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0006_rename_todoentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="text",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_list",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
